version: '3.8'
services:
  postgresql:
    image: postgres:15-alpine
    container_name: telegram-openapi-postgresql
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_ROOT_PASSWORD='
      - 'POSTGRES_USER='
      - 'POSTGRES_PASSWORD='
      - 'POSTGRES_DB=TelegramOpenAPIProjectDB'

  application:
    image: telegram-openapi-project
    container_name: telegram-openapi-application
    ports:
    - '8088:8088'
    environment:
      - 'DATABASE_URL=jdbc:postgresql://postgresql:5432/TelegramOpenAPIProjectDB'
      - 'DATABASE_USERNAME='
      - 'DATABASE_PASSWORD='
      - 'OPENAI_API_KEY='
      - 'TELEGRAM_BOT_TOKEN='
      - 'TZ=Europe/Kiev'
    depends_on:
      - postgresql